steps:
- name: gcr.io/k8s-skaffold/skaffold
  args:
    - skaffold
    - build
    - '--interactive=false'
    - '--file-output=/workspace/artifacts.json'
    - '--remote-cache-dir=/workspace/.skaffold/repos'
    - '--sync-remote-cache=always'
    - '--cache-file=/workspace/.skaffold/cache'
    - '--config=/workspace/.skaffold/config'
    - '--verbosity=debug'
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "hello-world-delivery-pipeline",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--build-artifacts", "/workspace/artifacts.json"
    ]
options:
  pool:
    name: 'projects/dev-demo-project-366116/locations/us-central1/workerPools/cicd-gke-private-pool-us-central1'
