apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: staging
description: Staging GKE Cluster
requireApproval: false
gke:
 cluster: projects/jlaude-labs-staging/locations/us-central1/clusters/jlaude-labs-staging-gke-cluster
