apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: Production GKE Cluster
requireApproval: true
gke:
 cluster: projects/jlaude-labs-prod/locations/us-central1/clusters/jlaude-labs-prod-gke-cluster
 internalIp: true
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  workerPool: projects/dev-demo-project-366116/locations/us-central1/workerPools/cicd-gke-private-pool-us-central1
  serviceAccount: cloud-deploy-prod-sa@dev-demo-project-366116.iam.gserviceaccount.com
