apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: Dev GKE Cluster
requireApproval: false
gke:
 cluster: projects/jlaude-labs-dev/locations/us-central1/clusters/jlaude-labs-dev-gke-cluster
   # internalIp: true
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  workerPool: projects/dev-demo-project-366116/locations/us-central1/workerPools/cicd-gke-private-pool-us-central1
  serviceAccount: cloud-deploy-dev-sa@dev-demo-project-366116.iam.gserviceaccount.com
