# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    tryImportMissing: true
  tagPolicy:
    inputDigest: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: us-central1-docker.pkg.dev/dev-demo-project-366116/jlaude-labs-repo/java-app-tier
      context: src/applicationtier
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      jib:
        args:
        - -Dmaven.test.skip=true
    - image: us-central1-docker.pkg.dev/dev-demo-project-366116/jlaude-labs-repo/java-web-app
      context: src/webservice
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      jib:
        args:
        - -Dmaven.test.skip=true

# defines the Kubernetes manifests to deploy on each run
profiles:
- name: staging
  deploy:
    kustomize:
      paths:
        - overlays/staging
- name: production
  deploy:
    kustomize:
      paths:
        - overlays/production
- name: dev
  deploy:
    kustomize:
      paths:
        - overlays/dev
