apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: prom-app-tier
spec:
  selector:
    matchLabels:
      app: java-app-tier
  endpoints:
  - port: metrics
    interval: 10s
    path: "/actuator/prometheus"
