bases:
- ../../base
commonLabels:
  env: prod
patches:
- path: replica_count.yaml
namePrefix: prod-
resources:
- nodeexporter.yaml
configMapGenerator:
  - name: config-properties
    files:
    - application.properties
