bases:
- ../../base
commonLabels:
  env: prod
patches:
- path: replica_count.yaml
resources:
- nodeexporter.yaml
- webClusterPodMonitoring.yaml
- appClusterPodMonitoring.yaml
configMapGenerator:
  - name: config-properties
    files:
    - application.properties
